version: "3"

services:
  beancount-trans-frontend:
    image: dhr2333/beancount-trans-frontend:latest
    # build:
    #   context: ./Beancount-Trans-Frontend
    #   dockerfile: Dockerfile
    #   args:
    #     - "--no-cache"
    container_name: beancount-trans-frontend
    restart: always
    ports:
      - "38001:80"
    volumes:
      - ./collectstatic:/code/beancount-trans/collectstatic
    depends_on:
      - beancount-trans-backend
  beancount-trans-backend:
    tty: true
    image: dhr2333/beancount-trans-backend:latest
    # build:
    #   context: ./Beancount-Trans-Backend
    #   dockerfile: Dockerfile-Backend
    #   args:
    #     - "--no-cache"
    container_name: beancount-trans-backend
    restart: always
    command: bash -c 'sh /code/beancount-trans/bin/docker_start.sh'
    # ports:
    #   - "38000:8000"
    volumes:
      - ./Beancount-Trans-Assets:/code/Beancount-Trans-Assets
      - ./collectstatic:/code/beancount-trans/collectstatic
    environment:
      - TRANS_MYSQL_DATABASE=beancount-trans
      - TRANS_MYSQL_USER=root
      - TRANS_MYSQL_PASSWORD=root
      - TRANS_MYSQL_HOST=beancount-trans-postgres
      - TRANS_MYSQL_PORT=5432
      - TRANS_REDIS_URL=redis://beancount-trans-redis:6379/
      - TRANS_REDIS_PASSWORD=root
    depends_on:
      - beancount-trans-postgres
      - beancount-trans-redis
  beancount-trans-postgres:
    image: dhr2333/beancount-trans-postgres:latest
    container_name: beancount-trans-postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - "postgres:/var/lib/postgresql/data"
  beancount-trans-redis:
    image: dhr2333/beancount-trans-redis:latest
    container_name: beancount-trans-redis
    restart: always
    ports:
      - "36379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - redis:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
  beancount-trans-assets:
    image: dhr2333/beancount-trans-assets:latest
    container_name: beancount-trans-assets
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./Beancount-Trans-Assets:/Assets
    environment:
      - BEANCOUNT_FILE=/Assets/main.bean
volumes:
  redis:
    # external: true # 若已创建外部存储卷，则取消该注释(多次docker compose up可能会导致存储卷重复创建导致启动失败)
    name: redis-data
  postgres:
    # external: true # 若已创建外部存储卷，则取消该注释
    name: postgres-data
