version: "3"

services:
  beancount-trans-frontend:
    # image: registry.cn-hangzhou.aliyuncs.com/dhr2333/beancount-trans-frontend:20240120
    build:
      context: ./Beancount-Trans-Frontend
      dockerfile: Dockerfile
      args:
        - "--no-cache"
    container_name: beancount-trans-frontend
    restart: always
    ports:
      - "38001:80"
    volumes:
      - ./collectstatic:/code/beancount-trans/collectstatic
    depends_on:
      - beancount-trans-backend
  beancount-trans-backend:
    tty: true
    # image: registry.cn-hangzhou.aliyuncs.com/dhr2333/beancount-trans-backend:20240120
    build:
      context: ./Beancount-Trans-Backend
      dockerfile: Dockerfile-Backend
      args:
        - "--no-cache"
    container_name: beancount-trans-backend
    restart: always
    command: bash -c 'sh /code/beancount-trans/bin/docker_start.sh'
    ports:
      - "38000:8000"
    volumes:
      - ./Beancount-Trans-Assets:/code/Beancount-Trans-Assets
      - ./collectstatic:/code/beancount-trans/collectstatic
    environment:
      - TRANS_MYSQL_DATABASE=beancount-trans
      - TRANS_MYSQL_USER=root
      - TRANS_MYSQL_PASSWORD=root
      - TRANS_MYSQL_HOST=beancount-trans-mysql
      - TRANS_MYSQL_PORT=3306
      - TRANS_REDIS_URL=redis://beancount-trans-redis:6379/
      - TRANS_REDIS_PASSWORD=root
    depends_on:
      - beancount-trans-mysql
      - beancount-trans-redis
  beancount-trans-mysql:
    # image: registry.cn-hangzhou.aliyuncs.com/dhr2333/beancount-trans-mysql:20240120
    build:
      context: ./Beancount-Trans-Backend
      dockerfile: Dockerfile-Mysql
      args:
        - "--no-cache"
    container_name: beancount-trans-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      # - mysql:/var/lib/mysql  # 若需要持久存储取消该注释和volumes中的注释
      - ./conf/my.cnf:/etc/mysql/my.cnf
    command: --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
  beancount-trans-redis:
    image: redis:7.0.4
    container_name: beancount-trans-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - redis:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
  beancount-trans-assets:
    image: yegle/fava:latest
    container_name: beancount-trans-assets
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./Beancount-Trans-Assets:/Assets
    environment:
      - BEANCOUNT_FILE=/Assets/main.bean
volumes:
  mysql:
    # external: true  # 若已创建外部存储卷，则取消该注释(多次docker compose up可能会导致存储卷重复创建导致启动失败)
    name: mysql-data
  redis:
    # external: true  # 若已创建外部存储卷，则取消该注释
    name: redis-data
